// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Check: typeof import('./components/Check.vue')['default']
    Filter: typeof import('./components/filter.vue')['default']
    FormField: typeof import('./components/FormField.vue')['default']
    InputNumber: typeof import('./components/Input/Number.vue')['default']
    InputSelect: typeof import('./components/Input/Select.vue')['default']
    InputText: typeof import('./components/Input/Text.vue')['default']
    InputTextarea: typeof import('./components/Input/Textarea.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./components/table.vue')['default']
  }
}
